<?php

use Illuminate\Database\Seeder;

class TblunitkerjaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tblunitkerja')->delete();
        
        \DB::table('tblunitkerja')->insert(array (
            0 => 
            array (
                'id' => 1,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ACCESIBILITY & ENVIRONMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ACCESIBILITY & ROAD',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ACCOUNT RECEIVABLE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ACCOUNT RECEIVABLE COLLECTION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AGREEMENT & COMMERCIAL CONTRACT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRCRAFT RESCUE & FIRE FIGHTING',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRFIELD',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRPORT DATA MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRPORT MAINTENANCE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRPORT OPERATION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRPORT OPERATION CENTER ',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRPORT OPERATION QUALITY CONTROL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRPORT RFF',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRPORT SECURITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRPORT SERVICE QUALITY CONTROL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRPORT SERVICES & FACILITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRSIDE INFRASTRUCTURE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRSIDE INFRASTRUCTURE & SUPPORT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRSIDE OPERATION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRSIDE OPERATION & ARFF',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AOCC',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'APMS Service',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'APRON MANAGEMENT SERVICE - T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'APRON MANAGEMENT SERVICE - T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'APRON MANAGEMENT SERVICE – T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ASSETS & LOGISTIC MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ASSETS MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AVIATION SECURITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AVIATION SECURITY - T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AVIATION SECURITY – T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AVIATION SECURITY – T3 DOMESTIC',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AVIATION SECURITY – T3 INTERNATIONAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'BAGGAGE HANDLING SYSTEM',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'BANDARA SOEKARNO-HATTA',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'BRANCH COMMUNICATION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'BRANCH COMMUNICATION & LEGAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'BUDGETING',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'BUILDING RESCUE & FIRE FIGHTING',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'CARGO SECURITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'CARGO SERVICE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'CASH MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'id_kategori_unit_kerja_fk' => NULL,
            'nama_uk' => 'CLOSED CIRCUIT TELEVISION (CCTV)',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'COMMUNICATION & DATA NETWORK',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'COMMUNITY DEVELOPMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'DATA NETWORK & IT NON PUBLIC SERVICE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'DIGITAL SERVICE – T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'DIGITAL SERVICE – T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'DIGITAL SERVICE – T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ELECTRICAL & MECHANICAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ELECTRICAL FACILITY – NON TERMINAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ELECTRICAL FACILITY – T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ELECTRICAL FACILITY – T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ELECTRICAL FACILITY – T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ELECTRICAL NETWORK ',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ELECTRICAL PROTECTION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ENERGY & POWER SUPPLY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ENVIRONMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'EQUIPMENT & WORKSHOP',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'EXECUTIVE GENERAL MANAGER',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'FINANCE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'FINANCE & HUMAN RESOURCES ',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'FINANCIAL CONTROL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'FINANCIAL MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'FIXED ASSET MANAGEMENT ',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'GENERAL & OPERATIONAL BUILDING',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'GENERAL ACCOUNTING',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'GENERAL AFFAIRS',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'GENERAL ELECTRONICS FACILITY  - T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'GENERAL ELECTRONICS FACILITY  - T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'GENERAL ELECTRONICS FACILITY – NON TERMINAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'GENERAL ELECTRONICS FACILITY – T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'GROUND SUPPORT SYSTEM',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'HIRING & PEOPLE MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'HIRING ADMINISTRATION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'HUMAN RESOURCES & GENERAL AFFAIRS',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'HUMAN RESOURCES ADMINISTRATION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'INTERNAL AFFAIRS ',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'INVENTORY & WAREHOUSE MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'INVENTORY MANAGEMENT ',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'IT NON PUBLIC SERVICE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'IT PUBLIC SERVICE & SECURITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'LAND MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'LANDSCAPE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'LANDSIDE & CARGO SERVICE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'LANDSIDE FACILITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'LANDSIDE SERVICE & FACILITY  ',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'LANDSIDE SERVICES',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'LEGAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MAIN POWER STATION 1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MAIN POWER STATION 2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MAIN POWER STATION 3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MAINTENANCE QUALITY CONTROL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MANAGEMENT ACCOUNTING',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MECHANICAL & AIRPORT EQUIPMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MECHANICAL FACILITY – NON TERMINAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MECHANICAL FACILITY – T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MECHANICAL FACILITY – T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MECHANICAL FACILITY – T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'MONITORING & REPORTING',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'NON TERMINAL & TRAFFIC',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'NORTH RUNWAY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'NORTH VISUAL AID',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'OFFICE MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'OFFICER IN CHARGE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'OPERATION & SERVICES PROCUREMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PASSENGER SERVICE – T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PASSENGER SERVICES - T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PASSENGER SERVICE-T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PEOPLE MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PERIMETER & VITAL OBJECT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PLANNING & DISTRIBUTION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PROCUREMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PROCUREMENT CONTRACT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PROTOCOL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PUBLIC RELATIONS',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PUBLIC SECURITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PUBLIC SECURITY - T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PUBLIC SECURITY - T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PUBLIC SECURITY - T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PUBLIC SERVICE & IT SYSTEM',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'RECEIVABLES ADMINISTRATION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'RFF EXERCISE & FACILITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SAFETY & RISK MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SAFETY & SECURITY  IT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SAFETY & SECURITY FACILITY – NON TERMINAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SAFETY & SECURITY FACILITY – T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SAFETY & SECURITY FACILITY – T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SAFETY & SECURITY FACILITY – T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SAFETY, RISK, & QUALITY CONTROL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SANITATION FACILITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SOUTH RUNWAY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SUBSIDIARY & SUPPORTING PROCUREMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TAX MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL BUILDING – T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL BULDING – T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL BULDING – T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL FACILITY - T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL FACILITY - T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL INSPECTION – T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL INSPECTION - T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL INSPECTION-T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL SERVICE - T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL SERVICE - T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL SERVICE - T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL SERVICE & FACILITY – T1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL SERVICE & FACILITY – T2',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TERMINAL SERVICE & FACILITY - T3',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TOC 1',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'TOD SERVICE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'UPS & CONVERTER',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'WAREHOUSE MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'WATER TREATMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'WELFARE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'WELFARE & HUMAN RESOURCES ADMINISTRATION',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'NDSIDE SERVICE & FACILITY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'AIRSIDE INFRASTRUCTURE & SUPPORT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ELECTRICAL & MECHANICAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'INFORMATION TECHNOLOGY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'INFORMATION TECHNOLOGY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'FINANCE',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'ASSETS & LOGISTIC MANAGEMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'HUMAN RESOURCES & GENERAL AFFAIRS',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'SAFETY',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'RISK',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => '& QUALITY CONTROL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'BRANCH COMMUNICATION & LEGAL',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'id_kategori_unit_kerja_fk' => NULL,
                'nama_uk' => 'PROCUREMENT',
                'jml_formasi' => 10,
                'jml_existing' => 0,
                'deleted_at' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}